### ISSUE TITLE
UpdateAvailability.UpdateNotAvailable for privately published apps?

### ISSUE THREAD

**Issue by slepmog** [PatGet/XamarinPlayCoreUpdater#11]
Tried to use this binding for a privately distributed app (published from the Google Admin console, as opposed to the Play Store console, as per https://support.google.com/a/answer/2494992?hl=en).

The code works (checks for updates, triggers `IOnSuccessListener.OnSuccess`), but inside `OnSuccess` the `appUpdateInfo.UpdateAvailability()` is always `UpdateAvailability.UpdateNotAvailable`.

At the same time, if we launch the Play Store app on the device and navigate to the "Work apps" tab (where all the admin-published apps appear), the updated version is there, and we can press Update to update it.

So why would the library return `UpdateAvailability.UpdateNotAvailable`?
Is there something wrong with the binding, in the original library itself, or are privately published apps not supported in the first place?

**Comment by PatGet** [comment]
I use the binding for a managed work app so i can verify it works with public apps and work (Manged Google Play) Apps. 
As private Apps are not "fully" published (Certification Process, not visibility) in the Store and just made visible for your Org in the Play Store App i expect that private apps are just not supported.
But i have seen no docs explicitly mentioning that. soi would suggest to check with Google if it should be possible with private apps.

**Comment by slepmog** [comment]
Aha

The binding does work even for private apps!
It's just that it takes much longer for (I assume) the Play Core library to detect there is an update.

While the new version of a private app appears on the "Work apps" tab in the Play Store withing 10 minutes of publishing, it takes a couple of hours for it to appear on the "Updates" tab of the "My apps & games" screen, and it's only then that `UpdateAvailability()` returns that an update is available.

The only quirk I have noticed is that on the very first time that an update is detected, `UpdateAvailability()` returns `UpdateAvailability.UpdateAvailable`, but `IsUpdateTypeAllowed(AppUpdateType.Immediate)` returns `false`, which I thought [was not even an option](https://stackoverflow.com/a/56806696/11683). On a second launch of the app though, it again reports `UpdateAvailability.UpdateAvailable`, and this time `IsUpdateTypeAllowed` is finally `true`.

**Comment by PatGet** [comment]
Yes, appearance on the update screen is needed before the api works, good that you gave it a second try.
What happens when you start the update flow even with allowed set to false?

**Comment by slepmog** [comment]
> What happens when you start the update flow even with allowed set to false?

I don't know! The code did not try to do that, only reported that it was the case. And it has not happened a second time so far, so cannot even test on purpose.

Believe this can be closed, thank you!
