### ISSUE TITLE
Add support for Api 27 and below

### ISSUE THREAD

**Issue by FabriBertani** [PatGet/XamarinPlayCoreUpdater#13]
Hello, i would like to know if there is any chance to add support for api 27 or below (like MonoAndroid80 and MonoAndroid81 e.g.) ?

**Comment by PatGet** [comment]
Hi Fabri,

why would you like to have that support?
This packages only works when you are in the Play Store and the minimum Version to be in the Play Store is API Level 29 according to https://devblogs.microsoft.com/xamarin/android-10-requirements/

Correct me if I´m wrong but there is no use case for older Versions.

**Comment by FabriBertani** [comment]
Ok, but does the implementation works if i download an app with android 8 or 7 from the store ? I tried with this package and if I try to use in-app rate with an Android 9 device it works fine, but when I try on Android 8 device it didn't work. As far as I know the original package from google have backward compatibility.

**Comment by PatGet** [comment]
https://developer.android.com/guide/playcore/in-app-review says: 

> > In-app reviews only work on the following devices:
> 
> - Android devices (phones and tablets) running Android 5.0 (API level 21) or higher that have the Google Play Store installed.



So i would expect it should work.

**Comment by saamerm** [comment]
@FabriBertani Are you still facing an issue?

**Comment by FabriBertani** [comment]
You can close it 👍

**Comment by saamerm** [comment]
@PatGet I don't have permissions to close this
