### ISSUE TITLE
Cannot resolve symbol 'SetUpdateAvailable'

### ISSUE THREAD

**Issue by eman1986** [PatGet/XamarinPlayCoreUpdater#14]
I'm attempting to use ```FakeAppUpdateManager``` to test the in-app update code and the sample project shows the use of

```
appUpdateManager.SetUpdateAvailable(2);
```

but when I try to use that I get the following error:

> Cannot resolve symbol 'SetUpdateAvailable'

**Comment by saamerm** [comment]
@eman1986 is that a warning or an error?

**Comment by eman1986** [comment]
It's an error

**Comment by saamerm** [comment]
Sorry I didn't see this earlier. But could you provide the stack trace, and place an exception catchpount and see if you get any additional details?

**Comment by eman1986** [comment]
There's no stack trace, it literally can't find that class so it doesn't even build

**Comment by saamerm** [comment]
Could you please share a screenshot of your Build settings in the Android project settings?

**Comment by saamerm** [comment]
@eman1986

**Comment by eman1986** [comment]
I'll try to get you something tomorrow

**Comment by eman1986** [comment]
ok so after try to recreate that issue I can't. not sure what I did wrong but it looks to be working fine now.
